/* ============================================================
   Turn the demo dataset into SQL for the platform database.

   Run once, review the output, apply it through
   AcademyManager/scripts/migrate.sh like any other migration.

     npm run export-seed > ../AcademyManager/supabase/migrations/00NN-mpp-seed.sql

   Why generate rather than hand-write the SQL: buildSeedData() already
   encodes how many students are in each batch, who has paid which
   month, who left and came back. Rewriting that by hand in SQL would
   produce a second, subtly different dataset — and the whole point of
   this move is to stop having two implementations of the same thing.

   This is a ONE-SHOT. Once the tenant is on Postgres, seed.ts is dead
   and the database is the only source of the numbers.
   ============================================================ */

import { buildSeedData } from '../src/lib/seed'
import type { Batch, Student, Transaction } from '../src/lib/types'

const T = 'mpp'

/** SQL string literal. Nothing here is user input, but a stray apostrophe
    in a name would still break the file, and "Ramu's" is a plausible note. */
function q(v: string | null | undefined): string {
  if (v === null || v === undefined || v === '') return 'null'
  return `'${String(v).replace(/'/g, "''")}'`
}
function n(v: number | null | undefined): string {
  return v === null || v === undefined || Number.isNaN(v) ? 'null' : String(v)
}

/** MPP stores day names; the shared schema stores ISO day numbers. */
const DAY_NUM: Record<string, number> = { Mon: 1, Tue: 2, Wed: 3, Thu: 4, Fri: 5, Sat: 6, Sun: 7 }
function daysArray(days?: string[]): string {
  // batches.days is NOT NULL. An empty array is the honest value for a
  // batch with no fixed days — Membership is open play, booked ad hoc —
  // and it keeps "which days?" answerable rather than unknown.
  const nums = (days ?? []).map((d) => DAY_NUM[d]).filter(Boolean)
  return nums.length ? `array[${nums.join(',')}]::int[]` : `'{}'::int[]`
}

/* The shared batches table has start_time and end_time NOT NULL: every
   coaching batch meets at a time. MPP's "Membership" is not a coaching
   batch — it is open play, booked ad hoc — so it has no slot at all.
   Rather than invent a time, it takes the venue's opening hours, which
   is genuinely when a member may turn up. If more tenants sell open
   play, the honest fix is a nullable slot on the shared table; one
   tenant with one such product does not justify that yet.

   The venue is open 5 AM to 1 AM, but batches carries a
   batches_time_order check (end > start) that a slot crossing midnight
   cannot satisfy. Clamped to end of day. The real hours stay correct in
   tenants.config.venues.narsingi.hours, which is what the app shows. */
const VENUE_OPEN: [string, string] = ['05:00', '23:59']

/** "4:30 PM – 5:30 PM" -> ['16:30','17:30']. */
function parseSlot(slot?: string): [string, string] {
  if (!slot) return VENUE_OPEN
  const m = slot.match(/(\d{1,2}):(\d{2})\s*([AP]M)\s*[–-]\s*(\d{1,2}):(\d{2})\s*([AP]M)/i)
  if (!m) return VENUE_OPEN
  const to24 = (h: string, mm: string, ap: string) => {
    let hh = parseInt(h, 10)
    if (/pm/i.test(ap) && hh !== 12) hh += 12
    if (/am/i.test(ap) && hh === 12) hh = 0
    return `${String(hh).padStart(2, '0')}:${mm}`
  }
  return [to24(m[1], m[2], m[3]), to24(m[4], m[5], m[6])]
}

function slug(s: string): string {
  return s.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '').slice(0, 40)
}

const data = buildSeedData()
const out: string[] = []
const p = (s = '') => out.push(s)

p('-- ============================================================')
p('-- Match Point Pride — sample data')
p('-- scope: mpp')
p('--')
p('-- GENERATED by MatchPointPride/scripts/export-seed-sql.ts from the')
p("-- app's own buildSeedData(). Do not hand-edit; regenerate.")
p('--')
p('-- Sample data, clearly marked. It exists so the owner can be shown a')
p('-- working app before he has typed anything, and so the console has')
p('-- something to display. Every member row carries is_demo = true, so')
p('-- the whole lot can be removed with one delete on the day he')
p('-- onboards for real.')
p('-- ============================================================')
p()
p('-- Idempotent: re-running replaces the sample set rather than doubling it.')
p("delete from payments    where tenant_id = 'mpp' and ref like 'SEED-%';")
// Expenses were missed the first time round, so re-running 0019 on top
// of 0018 doubled them: 32 became 64. Idempotency you have not tested
// by running it twice is a guess.
p("delete from expenses    where tenant_id = 'mpp' and ref like 'SEED-%';")
p("delete from reminder_events where tenant_id = 'mpp';")
p("delete from attendance  where tenant_id = 'mpp' and kind = 'staff';")
p("delete from enrollments where tenant_id = 'mpp' and member_id in")
p("  (select id from members where tenant_id = 'mpp' and is_demo);")
p("delete from members     where tenant_id = 'mpp' and is_demo;")
p("delete from fee_rules   where tenant_id = 'mpp' and note = 'seed';")
p("delete from batches     where tenant_id = 'mpp';")
p("delete from coaches     where tenant_id = 'mpp';")
p()
p('do $$')
p('declare')
p('  v_centre bigint;')
p('  v_batch  bigint;')
p('  v_member bigint;')
p('  v_enr    bigint;')
p('begin')
p("  select id into v_centre from centres where tenant_id = 'mpp' and code = 'narsingi';")
p("  if v_centre is null then raise exception 'mpp centre missing — apply 0008 first'; end if;")
p()

/* ---------- coaches ---------- */
p('  -- staff')
for (const s of data.staff) {
  p(`  insert into coaches (tenant_id, name, role, phone, active)`)
  p(`  values ('${T}', ${q(s.name)}, ${q(s.role)}, ${q(s.phone || null)}, ${s.active});`)
}
p()

/* ---------- batches + one fee rule each ---------- */
p('  -- batches, each with the fee rule that resolve_fee() will find')
const batchVar: Record<string, string> = {}
for (const b of data.batches as Batch[]) {
  const [st, en] = parseSlot(b.slot)
  batchVar[b.id] = slug(b.name)
  p(`  insert into batches (tenant_id, centre_id, code, name, sport, days, start_time, end_time, capacity, active, sort)`)
  p(`  values ('${T}', v_centre, ${q(slug(b.name))}, ${q(b.name)}, 'badminton', ${daysArray(b.days)},`)
  p(`          ${q(st)}, ${q(en)}, ${n(b.capacity)}, true, ${b.colorSlot})`)
  p(`  returning id into v_batch;`)
  p(`  insert into fee_rules (tenant_id, label, centre_id, sport, batch_id, monthly_amount,`)
  p(`                         plan_amounts, admission_fee, effective_from, active, note)`)
  p(`  values ('${T}', ${q(b.name)}, v_centre, 'badminton', v_batch, ${n(b.fee)},`)
  p(`          '{}'::jsonb, 0, current_date - 400, true, 'seed');`)
  p()
}

/* ---------- members + enrolments ---------- */
const byBatch: Record<string, Batch> = {}
for (const b of data.batches as Batch[]) byBatch[b.id] = b

/* Where each student's renewal falls, relative to today.

   Setting them all to "the 1st of this month" made 46 of 49 read as 28
   days overdue, which is not an academy — it is a bug that happens to
   parse. It also put every single student past the ladder's +15 line,
   where reminder_queue stops chasing and hands over to manual, so the
   demo would have shown an app with nothing to do.

   This spread is a plausible month: most parents have paid and are not
   due for weeks, a couple are approaching, and a handful sit at each
   rung of the ladder — -2 heads-up, 0 due, +5 first chase, +7 to +14
   daily. Exactly one is past +15, because that case needs to be
   visible too. */
const RENEWAL_SPREAD = [
  25, 21, 18, 17, 14, 12, 11, 9, 8, 7, 6, 4, 3, 1,   // paid, not yet due
  2, -0, -5, -8, -11, -16,                            // the ladder, in order
  27, 24, 22, 19, 16, 15, 13, 10,                     // more not-due
]
function renewalOffset(i: number): number {
  return RENEWAL_SPREAD[i % RENEWAL_SPREAD.length]
}

p('  -- students, as members + the enrolment that carries the money')
let idx = -1
for (const s of data.students as Student[]) {
  idx++
  const b = byBatch[s.batchId]
  if (!b) continue
  const spells = s.spells?.length ? s.spells : [{ from: s.joinedOn }]
  const first = spells[0]
  const last = spells[spells.length - 1]
  const discontinued = !s.active
  p(`  insert into members (tenant_id, name, parent_name, parent_phone, program, joined, status, venue, is_demo, notes)`)
  p(`  values ('${T}', ${q(s.name)}, ${q(s.guardian || null)}, ${q(s.phone)}, 'badminton',`)
  p(`          ${q(first.from)}::date, ${discontinued ? "'discontinued'" : "'active'"}, 'narsingi', true, ${q(s.note || null)})`)
  p(`  returning id into v_member;`)
  p(`  insert into enrollments (tenant_id, member_id, centre_id, batch_id, sport, plan_months,`)
  p(`                           joined_on, renewal_on, status, discontinued_on)`)
  p(`  values ('${T}', v_member, v_centre, (select id from batches where tenant_id='${T}' and code=${q(slug(b.name))}),`)
  p(`          'badminton', 1, ${q(last.from)}::date,`)
  p(`          current_date + ${renewalOffset(idx)},`)
  p(`          ${discontinued ? "'discontinued'" : "'active'"}, ${last.to ? `${q(last.to)}::date` : 'null'})`)
  p(`  returning id into v_enr;`)

  /* The fees this student has actually paid, through the one write path.
     record_fee_payment is what sets period_from/period_to — the record of
     which month a payment covers — and without it the app reads every
     student as never having paid, which is what the first seed did. */
  const paid = (data.transactions as Transaction[]).filter(
    (t) => t.type === 'revenue' && t.source === 'student_fee' && t.studentId === s.id,
  )
  for (const t of paid) {
    p(`  perform record_fee_payment('${T}', v_enr, ${n(Math.round(t.amount))}, 1, 'UPI', 'renewal',`)
    p(`                             ${q(t.date)}::date, ${q(`SEED-F-${s.id}-${t.date}`)});`)
  }
  /* record_fee_payment rolls renewal_on forward on every payment, which
     is correct behaviour and exactly why it cannot be left where it
     lands here: the spread below is what puts one student on each rung
     of the ladder. Set after, not before. */
  p(`  update enrollments set renewal_on = current_date + ${renewalOffset(idx)} where id = v_enr;`)
}
p()

/* ---------- money ---------- */
const revenue = (data.transactions as Transaction[]).filter((t) => t.type === 'revenue')
const expenses = (data.transactions as Transaction[]).filter((t) => t.type === 'expense')

p(`  -- revenue not tied to an enrolment (court hire, memberships, sundry)`)
for (const [i, t] of revenue.filter((t) => t.source !== 'student_fee').entries()) {
  const type = t.source === 'court_booking' ? 'Court' : t.source === 'membership' ? 'Membership' : 'Coaching'
  p(`  insert into payments (tenant_id, name, type, detail, amount, mode, on_date, ref, status, kind)`)
  p(`  values ('${T}', ${q(t.category)}, ${q(type)}, ${q(t.note || null)}, ${n(Math.round(t.amount))},`)
  p(`          'UPI', ${q(t.date)}::date, ${q(`SEED-R${i}`)}, 'paid', null);`)
}
p()
p('  -- expenses')
for (const [i, t] of expenses.entries()) {
  p(`  insert into expenses (tenant_id, ref, category, payee, detail, amount, mode, on_date)`)
  p(`  values ('${T}', ${q(`SEED-E${i}`)}, ${q(t.category)}, null, ${q(t.note || null)},`)
  p(`          ${n(Math.round(t.amount))}, 'UPI', ${q(t.date)}::date);`)
}
p()

/* ---------- staff attendance ---------- */
p('  -- staff attendance, last 30 days')
p(`  insert into attendance (tenant_id, date, kind, person_id, present)`)
p(`  select '${T}', d::date, 'staff', c.id::text, true`)
p(`    from generate_series(current_date - 29, current_date, interval '1 day') d`)
p(`    cross join (select id from coaches where tenant_id = '${T}') c`)
p(`   where extract(isodow from d) <> 7`)
p(`  on conflict do nothing;`)
p()
p('end $$;')
p()

/* ---------- per-batch UPI, in config ---------- */
p('-- Per-batch UPI ids. These live in tenants.config rather than a new')
p('-- column on the shared batches table, per the platform rule that')
p('-- per-tenant behaviour goes in config jsonb.')
/* The demo dataset carries invented handles (matchpointkids@ybl and
   friends). Those must NOT reach the database: a UPI id that looks real
   but belongs to nobody — or worse, to someone else — is how a parent's
   fee goes to a stranger. Sample data may be fake; payment destinations
   may not. Every batch gets the academy's real handle, which is already
   in tenants.config.billing, and the owner can split them later. */
const REAL_UPI = '7732077327@ybl'
const REAL_PAYEE = 'Match Point Badminton Academy'
const upi: Record<string, { upi: string; payee: string }> = {}
for (const b of data.batches as Batch[]) {
  upi[slug(b.name)] = { upi: REAL_UPI, payee: REAL_PAYEE }
}
// One flat merge. The nested jsonb_build_object version was miscounted
// twice; a single jsonb literal merged at one level cannot be.
p(`update tenants`)
p(`   set config = jsonb_set(coalesce(config, '{}'::jsonb), '{billing,upiByBatch}',`)
p(`         '${JSON.stringify(upi).replace(/'/g, "''")}'::jsonb, true)`)
p(` where id = 'mpp';`)
p()

/* ---------- assertions ---------- */
p('-- Prove the shape, and that the money chain resolves for a real batch.')
p('do $$')
p('declare v_b int; v_m int; v_e int; v_c int; v_fee jsonb; v_batch bigint;')
p('begin')
p("  select count(*) into v_b from batches where tenant_id='mpp';")
p("  select count(*) into v_m from members where tenant_id='mpp' and is_demo;")
p("  select count(*) into v_e from enrollments where tenant_id='mpp';")
p("  select count(*) into v_c from coaches where tenant_id='mpp';")
p(`  if v_b <> ${data.batches.length} then raise exception 'batches: expected ${data.batches.length}, got %', v_b; end if;`)
p(`  if v_m <> ${data.students.length} then raise exception 'members: expected ${data.students.length}, got %', v_m; end if;`)
p(`  if v_e <> ${data.students.length} then raise exception 'enrollments: expected ${data.students.length}, got %', v_e; end if;`)
p(`  if v_c <> ${data.staff.length} then raise exception 'coaches: expected ${data.staff.length}, got %', v_c; end if;`)
p()
p("  select id into v_batch from batches where tenant_id='mpp' and code='kids-batch-a';")
p("  v_fee := resolve_fee('mpp', null, (select id from centres where tenant_id='mpp' and code='narsingi'),")
p("                       'badminton', v_batch, 1, null);")
p("  if (v_fee->>'source') <> 'batch' then")
p("    raise exception 'fee for Kids Batch A resolved from %, not the batch rule', v_fee->>'source';")
p('  end if;')
p(`  if (v_fee->>'amount')::numeric <> 2000 then`)
p("    raise exception 'Kids Batch A fee is %, expected 2000', v_fee->>'amount';")
p('  end if;')
p()
p("  raise notice 'mpp seeded: % batches, % members, % coaches', v_b, v_m, v_c;")
p('end $$;')

process.stdout.write(out.join('\n') + '\n')
